# Generated by Django 6.0.5 on 2026-05-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAccionIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la acción')),
                ('porcentaje', models.FloatField(help_text='Porcentaje de avance asociado (ej: 12.5)')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoAccionSEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la acción')),
                ('porcentaje', models.FloatField(help_text='Porcentaje de avance asociado (ej: 14.3)')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionLey1620',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAgresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CasoSIUCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado_sac', models.CharField(max_length=50, verbose_name='Radicado SAC asociado')),
                ('estudiante_victima', models.CharField(max_length=255, verbose_name='Víctima')),
                ('nombre_agresor', models.CharField(max_length=255, verbose_name='Nombre del Agresor/Involucrado')),
                ('avance_ie', models.FloatField(default=0.0, verbose_name='Avance I.E.')),
                ('avance_sem', models.FloatField(default=0.0, verbose_name='Avance S.E.M.')),
                ('avance_general', models.FloatField(default=0.0, verbose_name='Avance Total (%)')),
                ('estado', models.CharField(default='PENDIENTE', max_length=20, verbose_name='Estado del Caso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('accion_ie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siuce.catalogoaccionie', verbose_name='Acción I.E.')),
                ('accion_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siuce.catalogoaccionsem', verbose_name='Acción S.E.M.')),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siuce.clasificacionley1620')),
                ('evento_generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siuce.eventogenerador')),
                ('tipo_agresion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siuce.tipoagresion')),
                ('tipos_dano', models.ManyToManyField(to='siuce.tipodano', verbose_name='Tipos de Daño')),
            ],
            options={
                'db_table': 'caso_siuce',
            },
        ),
    ]
