# Generated by Django 6.0.5 on 2026-05-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoSIUCE',
            fields=[
                ('radicado', models.IntegerField(primary_key=True, serialize=False)),
                ('avance_ie', models.FloatField(default=0.0)),
                ('avance_sem', models.FloatField(default=0.0)),
                ('avance_general', models.FloatField(default=0.0, editable=False)),
                ('estado', models.CharField(default='PENDIENTE', editable=False, max_length=20)),
                ('tipo_agresion', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=10)),
            ],
        ),
    ]
