# Generated by Django 6.0.5 on 2026-06-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Clasificación')),
            ],
            options={
                'verbose_name': 'Clasificación de Caso',
                'verbose_name_plural': 'Clasificaciones de Casos',
                'db_table': 'Clasificacion_caso',
            },
        ),
        migrations.CreateModel(
            name='EstadoSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sac', models.CharField(max_length=255, verbose_name='Nombre del Estado')),
            ],
            options={
                'verbose_name': 'Estado SAC',
                'verbose_name_plural': 'Estados SAC',
                'db_table': 'Estados_SAC',
            },
        ),
        migrations.CreateModel(
            name='RespuestaSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_sac', models.CharField(max_length=255, verbose_name='Nombre de la Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta SAC',
                'verbose_name_plural': 'Respuestas SAC',
                'db_table': 'Respuestas_SAC',
            },
        ),
        migrations.CreateModel(
            name='RolCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=255, verbose_name='Nombre del Rol')),
            ],
            options={
                'verbose_name': 'Rol de Ciudadano',
                'verbose_name_plural': 'Roles de Ciudadanos',
                'db_table': 'Rol_Ciudadano',
            },
        ),
    ]
