# Generated by Django 6.0.5 on 2026-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionesIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_accion_ie', models.CharField(max_length=255, verbose_name='Nombre de la Acción de la Institución Educativa')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de la Acción')),
            ],
            options={
                'verbose_name': 'Acción de IE',
                'verbose_name_plural': 'Acciones de IE',
                'db_table': 'Acciones_IE',
            },
        ),
        migrations.CreateModel(
            name='AccionesSEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_accion_sem', models.CharField(max_length=255, verbose_name='Nombre de la Acción de la SEM')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de la Acción')),
            ],
            options={
                'verbose_name': 'Acción de SEM',
                'verbose_name_plural': 'Acciones de SEM',
                'db_table': 'Acciones_SEM',
            },
        ),
        migrations.CreateModel(
            name='EstadoSIUCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_siuce', models.CharField(max_length=255, verbose_name='Nombre del Estado SIUCE')),
            ],
            options={
                'verbose_name': 'Estado SIUCE',
                'verbose_name_plural': 'Estados SIUCE',
                'db_table': 'Estados_SIUCE',
            },
        ),
        migrations.CreateModel(
            name='EventoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_generador', models.CharField(max_length=255, verbose_name='Nombre del Evento Generador')),
            ],
            options={
                'verbose_name': 'Evento Generador',
                'verbose_name_plural': 'Eventos Generadores',
                'db_table': 'Eventos_Generadores',
            },
        ),
        migrations.CreateModel(
            name='GradoEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grado', models.CharField(max_length=255, verbose_name='Nombre del Grado de Escolaridad')),
            ],
            options={
                'verbose_name': 'Grado de Escolaridad',
                'verbose_name_plural': 'Grados de Escolaridad',
                'db_table': 'Grados_Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='LugarHechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lugar', models.CharField(max_length=255, verbose_name='Nombre del Lugar de los Hechos')),
            ],
            options={
                'verbose_name': 'Lugar de los Hechos',
                'verbose_name_plural': 'Lugares de los Hechos',
                'db_table': 'Lugares_Hechos',
            },
        ),
        migrations.CreateModel(
            name='RolAgresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rol_agresor', models.CharField(max_length=255, verbose_name='Nombre del Rol del Agresor')),
            ],
            options={
                'verbose_name': 'Rol del Agresor',
                'verbose_name_plural': 'Roles de Agresores',
                'db_table': 'Rol_Agresor',
            },
        ),
        migrations.CreateModel(
            name='TipoAgresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agresion', models.CharField(max_length=255, verbose_name='Nombre del Tipo de Agresión')),
            ],
            options={
                'verbose_name': 'Tipo de Agresión',
                'verbose_name_plural': 'Tipos de Agresiones',
                'db_table': 'Tipos_Agresion',
            },
        ),
        migrations.CreateModel(
            name='TipoDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dano', models.CharField(max_length=255, verbose_name='Nombre del Tipo de Daño')),
            ],
            options={
                'verbose_name': 'Tipo de Daño',
                'verbose_name_plural': 'Tipos de Daños',
                'db_table': 'Tipos_Dano',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código del Tipo de Identificación')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Tipo de Identificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificaciones',
                'db_table': 'Tipos_Identificacion',
            },
        ),
    ]
