# Generated by Django 6.0.5 on 2026-06-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_accionesie_activo_accionessem_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoidentificacion',
            old_name='descripcion',
            new_name='tipo_identificacion',
        ),
        migrations.RemoveField(
            model_name='tipoidentificacion',
            name='codigo',
        ),
    ]
