# Generated by Django 6.0.5 on 2026-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_institucioneducativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
