# Generated by Django 6.0.5 on 2026-06-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_institucioneducativa_activo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clasificacioncaso',
            table='Clasificacion_caso',
        ),
    ]
