# Generated by Django 6.0.5 on 2026-06-24 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_alter_clasificacioncaso_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='cod_dane',
            field=models.CharField(default='000000000000', max_length=12, validators=[django.core.validators.RegexValidator(message='El código DANE debe tener exactamente 12 dígitos numéricos.', regex='^\\d{12}$')], verbose_name='Código DANE'),
            preserve_default=False,
        ),
    ]
