# Generated by Django 6.0.5 on 2026-06-28 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_institucioneducativa_cod_dane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='cod_dane',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El código DANE debe tener exactamente 12 dígitos numéricos.', regex='^\\d{12}$')], verbose_name='Código DANE'),
        ),
    ]
