# Generated by Django 6.0.5 on 2026-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('lider', 'Líder')], default='lider', max_length=20, verbose_name='Rol'),
        ),
    ]
