# Generated by Django 6.0.5 on 2026-06-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_completo',
        ),
    ]
