# Generated by Django 6.0.5 on 2026-07-03 02:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0009_alter_institucioneducativa_cod_dane'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoSIUCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_radicado_siuce', models.CharField(max_length=15, verbose_name='Radicado SIUCE')),
                ('avance_general', models.FloatField(default=0.0, verbose_name='Avance Total (%)')),
                ('estudiante_victima', models.CharField(max_length=255, verbose_name='Víctima')),
                ('num_indentificacion', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('repetitivo', models.BooleanField(default=False, verbose_name='¿Es Repetitivo?')),
                ('otro_evento_generador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro Evento Generador')),
                ('nombre_agresor', models.CharField(max_length=255, verbose_name='Agresor/Involucrado')),
                ('fecha_ocurrencia', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ocurrencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('seguimiento_ie', models.BooleanField(default=False, verbose_name='En Seguimiento I.E.')),
                ('num_seguimiento_ie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seguimiento I.E.')),
                ('seguimiento_policia', models.BooleanField(default=False, verbose_name='En Seguimiento Policía')),
                ('num_seguimiento_policia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Seguimiento Policía')),
                ('cec', models.BooleanField(default=False, verbose_name='¿Caso llevado a Comité Curricular?')),
                ('porcentaje_avance_ie', models.FloatField(default=0.0, verbose_name='Porcentaje de Avance I.E.')),
                ('porcentaje_avance_sem', models.FloatField(default=0.0, verbose_name='Porcentaje de Avance S.E.M.')),
                ('descripcion_avance', models.TextField(blank=True, null=True, verbose_name='Descripción del Caso')),
                ('rad_entidad_ext', models.CharField(blank=True, max_length=255, null=True, verbose_name='Radicados en Entidades Externas')),
                ('fecha_rad_entidad_ext', models.DateField(blank=True, null=True, verbose_name='Fecha de Radicación en Entidades Externas')),
                ('accion_ie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.accionesie', verbose_name='Acción I.E.')),
                ('accion_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.accionessem', verbose_name='Acción S.E.M.')),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.clasificacioncaso', verbose_name='Clasificación del Caso')),
                ('dano_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caso_siuce_dano_principal', to='catalogos.tipodano', verbose_name='Daño Principal')),
                ('dano_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caso_siuce_dano_secundario', to='catalogos.tipodano', verbose_name='Daño Secundario')),
                ('dano_terciario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caso_siuce_dano_terciario', to='catalogos.tipodano', verbose_name='Daño Terciario')),
                ('estado_siuce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadosiuce', verbose_name='Estado SIUCE')),
                ('evento_generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.eventogenerador', verbose_name='Evento Generador')),
                ('grado_escolaridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.gradoescolaridad', verbose_name='Grado de Escolaridad')),
                ('institucion_educativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.institucioneducativa', verbose_name='Institución Educativa')),
                ('lugar_hechos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.lugarhechos', verbose_name='Lugar de los Hechos')),
                ('rol_agresor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.rolagresor', verbose_name='Rol del Agresor')),
                ('tipo_agresion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoagresion', verbose_name='Tipo de Agresión')),
                ('tipo_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoidentificacion', verbose_name='Tipo de Identificación')),
            ],
            options={
                'verbose_name': 'Caso SIUCE',
                'verbose_name_plural': 'Casos SIUCE',
                'db_table': 'Caso_SIUCE',
            },
        ),
    ]
