# Generated by Django 6.0.5 on 2026-06-12 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_accionesie_accionessem_estadosiuce_eventogenerador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoSIUCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado_sac', models.CharField(max_length=50, verbose_name='Radicado SAC asociado')),
                ('estudiante_victima', models.CharField(max_length=255, verbose_name='Víctima')),
                ('nombre_agresor', models.CharField(max_length=255, verbose_name='Agresor/Involucrado')),
                ('avance_ie', models.FloatField(default=0.0, verbose_name='Avance I.E.')),
                ('avance_sem', models.FloatField(default=0.0, verbose_name='Avance S.E.M.')),
                ('avance_general', models.FloatField(default=0.0, verbose_name='Avance Total (%)')),
                ('estado', models.CharField(default='PENDIENTE', max_length=20, verbose_name='Estado del Caso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('accion_ie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.accionesie', verbose_name='Acción I.E.')),
                ('accion_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.accionessem', verbose_name='Acción S.E.M.')),
                ('estado_siuce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadosiuce', verbose_name='Estado SIUCE')),
                ('evento_generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.eventogenerador', verbose_name='Evento Generador')),
                ('grado_escolaridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.gradoescolaridad', verbose_name='Grado de Escolaridad')),
                ('lugar_hechos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.lugarhechos', verbose_name='Lugar de los Hechos')),
                ('rol_agresor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.rolagresor', verbose_name='Rol del Agresor')),
                ('tipo_agresion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoagresion', verbose_name='Tipo de Agresión')),
                ('tipo_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoidentificacion', verbose_name='Tipo de Identificación')),
                ('tipos_dano', models.ManyToManyField(to='catalogos.tipodano', verbose_name='Tipos de Daño')),
            ],
            options={
                'verbose_name': 'Caso SIUCE',
                'verbose_name_plural': 'Casos SIUCE',
                'db_table': 'Caso_SIUCE',
            },
        ),
    ]
