# Generated by Django 6.0.5 on 2026-06-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siuce', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para aplicar (Forward): Pasa de minúsculas al nombre con mayúsculas protegido
            sql='ALTER TABLE caso_siuce RENAME TO "Caso_SIUCE";',
            
            # SQL para revertir (Backward): Quita la protección para volver a minúsculas
            reverse_sql='ALTER TABLE "Caso_SIUCE" RENAME TO caso_siuce;'
        ),
    ]
