# Generated by Django 6.0.5 on 2026-07-03 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siuce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casosiuce',
            name='usuario_registro_siuce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_siuce_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
