# Generated by Django 6.0.5 on 2026-06-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siuce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casosiuce',
            options={'verbose_name': 'Caso SIUCE', 'verbose_name_plural': 'Casos SIUCE'},
        ),
    ]
