# Generated by Django 6.0.5 on 2026-07-15 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siuce', '0002_casosiuce_usuario_registro_siuce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casosiuce',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
    ]
