# Generated by Django 6.0.5 on 2026-06-14 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_rename_descripcion_tipoidentificacion_tipo_identificacion_and_more'),
        ('siuce', '0002_renombrar_tabla_caso_siuce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casosiuce',
            name='tipos_dano',
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='dano_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caso_siuce_dano_principal', to='catalogos.tipodano', verbose_name='Daño Principal'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='dano_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caso_siuce_dano_secundario', to='catalogos.tipodano', verbose_name='Daño Secundario'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='dano_terciario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='caso_siuce_dano_terciario', to='catalogos.tipodano', verbose_name='Daño Terciario'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='fecha_hechos',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de los Hechos'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='otro_evento_generador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro Evento Generador'),
        ),
    ]
