# Generated by Django 6.0.5 on 2026-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siuce', '0003_remove_casosiuce_tipos_dano_casosiuce_dano_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casosiuce',
            name='radicado_sac',
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='num_radicado_siuce',
            field=models.CharField(default=0, max_length=50, verbose_name='Radicado SIUCE'),
            preserve_default=False,
        ),
    ]
