# Generated by Django 6.0.5 on 2026-06-15 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_institucioneducativa'),
        ('siuce', '0004_remove_casosiuce_radicado_sac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casosiuce',
            name='avance_ie',
        ),
        migrations.RemoveField(
            model_name='casosiuce',
            name='avance_sem',
        ),
        migrations.RemoveField(
            model_name='casosiuce',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='casosiuce',
            name='fecha_hechos',
        ),
        migrations.RemoveField(
            model_name='casosiuce',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='cec',
            field=models.BooleanField(default=False, verbose_name='¿Caso llevado a Comité Curricular?'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.clasificacioncaso', verbose_name='Clasificación del Caso'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='descripcion_avance',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Caso'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='fecha_ocurrencia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ocurrencia'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='fecha_rad_entidad_ext',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Radicación en Entidades Externas'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='institucion_educativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.institucioneducativa', verbose_name='Institución Educativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='num_indentificacion',
            field=models.CharField(default=0, max_length=20, verbose_name='Número de Identificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='num_seguimiento_ie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Seguimiento I.E.'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='num_seguimiento_policia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Seguimiento Policía'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='porcentaje_avance_ie',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de Avance I.E.'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='porcentaje_avance_sem',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de Avance S.E.M.'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='rad_entidad_ext',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Radicados en Entidades Externas'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='repetitivo',
            field=models.BooleanField(default=False, verbose_name='¿Es Repetitivo?'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='seguimiento_ie',
            field=models.BooleanField(default=False, verbose_name='En Seguimiento I.E.'),
        ),
        migrations.AddField(
            model_name='casosiuce',
            name='seguimiento_policia',
            field=models.BooleanField(default=False, verbose_name='En Seguimiento Policía'),
        ),
        migrations.AlterField(
            model_name='casosiuce',
            name='num_radicado_siuce',
            field=models.CharField(max_length=15, verbose_name='Radicado SIUCE'),
        ),
    ]
