# Generated by Django 6.0.5 on 2026-06-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siuce', '0005_remove_casosiuce_avance_ie_and_more'),
    ]

    operations = [
    ]
