# Generated by Django 6.0.5 on 2026-06-17 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0006_institucioneducativa_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_radicado_sac', models.CharField(max_length=15, verbose_name='Radicado SIUCE')),
                ('ciudadano', models.CharField(max_length=255)),
                ('fecha_radicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ocurrencia')),
                ('radicado_respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('estudiante', models.CharField(max_length=255, verbose_name='Nombre Estudiante')),
                ('traslado_ie', models.BooleanField(default=False, verbose_name='Traslado IE')),
                ('num_radicado_traslado', models.CharField(blank=True, max_length=50, null=True)),
                ('radicado_externa', models.CharField(blank=True, max_length=50, null=True)),
                ('respondido', models.BooleanField(default=False, verbose_name='¿Respondido?')),
                ('prorroga', models.BooleanField(default=False, verbose_name='¿Prórroga?')),
                ('fecha_nueva_prorroga', models.DateField(blank=True, null=True, verbose_name='Fecha Nueva Prórroga')),
                ('radicado_prorroga', models.CharField(blank=True, max_length=50, null=True)),
                ('contestacion_ie', models.BooleanField(default=False)),
                ('radicado_contestacion_ie', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.clasificacioncaso', verbose_name='Clasificación del Caso')),
                ('estado_sac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadosac', verbose_name='Estado SAC')),
                ('institucion_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_1', to='catalogos.institucioneducativa')),
                ('institucion_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_2', to='catalogos.institucioneducativa')),
                ('rol_ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.rolciudadano', verbose_name='Rol del Ciudadano')),
                ('sac_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.respuestasac', verbose_name='Respuesta SAC')),
            ],
            options={
                'verbose_name': 'Caso SAC',
                'verbose_name_plural': 'Casos SAC',
                'db_table': 'Caso_SAC',
            },
        ),
    ]
