# Generated by Django 6.0.5 on 2026-06-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudSAC',
            fields=[
                ('radicado', models.CharField(help_text='Formato: CUCYYYYER######', max_length=20, primary_key=True, serialize=False)),
                ('ciudadano', models.CharField(max_length=255)),
                ('fecha_radicacion', models.DateField()),
                ('radicado_respuesta', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('EST', 'Estudiante'), ('DOC', 'Docente'), ('ADM', 'Administrativo'), ('PAD', 'Padre de Familia')], max_length=3)),
                ('traslado_ie', models.BooleanField(default=False)),
                ('ie_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('radicado_traslado', models.CharField(blank=True, max_length=20, null=True)),
                ('radicado_externa', models.CharField(blank=True, max_length=20, null=True)),
                ('respondido', models.BooleanField(default=False)),
                ('prorroga', models.BooleanField(default=False)),
                ('fecha_nueva_prorroga', models.DateField(blank=True, null=True)),
                ('radicado_prorroga', models.CharField(blank=True, max_length=20, null=True)),
                ('contestacion_ie', models.BooleanField(default=False)),
                ('radicado_contestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('estudiante', models.CharField(max_length=255)),
                ('institucion_involucrada', models.CharField(max_length=255)),
                ('situacion', models.CharField(max_length=10)),
                ('sac_respuesta', models.CharField(choices=[('ENV', 'ENVIADA'), ('NO', 'NO'), ('SI', 'SÍ')], max_length=3)),
                ('estado', models.CharField(choices=[('SEG', 'EN SEGUIMIENTO'), ('TER', 'TERMINADO')], max_length=3)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sac.institucion')),
                ('tipo_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sac.tipoidentificacion')),
            ],
        ),
    ]
