# Generated by Django 6.0.5 on 2026-06-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casosac',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.clasificacioncaso', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='estado_sac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadosac', verbose_name='Estado SAC'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='rol_ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.rolciudadano', verbose_name='Rol del Ciudadano'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='sac_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.respuestasac', verbose_name='Respuesta SAC'),
        ),
        migrations.AlterModelTable(
            name='casosac',
            table='Caso_SAC',
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
        migrations.DeleteModel(
            name='EstadoSAC',
        ),
        migrations.DeleteModel(
            name='RolCiudadano',
        ),
        migrations.DeleteModel(
            name='SACRespuesta',
        ),
    ]
