# Generated by Django 6.0.5 on 2026-06-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RolCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SACRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudsac',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='solicitudsac',
            name='tipo_identificacion',
        ),
        migrations.CreateModel(
            name='CasoSAC',
            fields=[
                ('num_rad_sac', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número Radicado')),
                ('ciudadano', models.CharField(max_length=255)),
                ('estudiante', models.CharField(max_length=255, verbose_name='Nombre Estudiante')),
                ('fecha_radicacion', models.DateField()),
                ('radicado_respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('radicado_externa', models.CharField(blank=True, max_length=50, null=True)),
                ('num_radicado_traslado', models.CharField(blank=True, max_length=50, null=True)),
                ('radicado_prorroga', models.CharField(blank=True, max_length=50, null=True)),
                ('radicado_contestacion', models.CharField(blank=True, max_length=50, null=True)),
                ('traslado_ie', models.BooleanField(default=False, verbose_name='Traslado IE')),
                ('respondido', models.BooleanField(default=False)),
                ('prorroga', models.BooleanField(default=False)),
                ('contestacion_ie', models.BooleanField(default=False)),
                ('fecha_nueva_prorroga', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac.clasificacion')),
                ('estado_sac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac.estadosac')),
                ('institucion_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_1', to='sac.institucioneducativa')),
                ('institucion_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_2', to='sac.institucioneducativa')),
                ('rol_ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sac.rolciudadano')),
                ('sac_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sac.sacrespuesta')),
            ],
            options={
                'verbose_name': 'Caso SAC',
                'verbose_name_plural': 'Casos SAC',
            },
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='SolicitudSAC',
        ),
        migrations.DeleteModel(
            name='TipoIdentificacion',
        ),
    ]
