# Generated by Django 6.0.5 on 2026-06-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casosac',
            table='caso_sac',
        ),
    ]
