# Generated by Django 6.0.5 on 2026-06-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_alter_clasificacioncaso_table'),
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casosac',
            name='contestacion_ie',
            field=models.BooleanField(default=False, verbose_name='Contestación IE'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='institucion_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_1', to='catalogos.institucioneducativa'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='radicado_prorroga',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radicado Prórroga'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='traslado_ie',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Traslado IE'),
        ),
    ]
