# Generated by Django 6.0.5 on 2026-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_alter_casosac_contestacion_ie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casosac',
            name='num_radicado_sac',
            field=models.CharField(max_length=15, unique=True, verbose_name='Radicado SIUCE'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='num_radicado_traslado',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='radicado_contestacion_ie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Radicado Contestación IE'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='radicado_externa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='radicado_respuesta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
