# Generated by Django 6.0.5 on 2026-06-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_institucioneducativa'),
        ('sac', '0002_alter_casosac_clasificacion_alter_casosac_estado_sac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casosac',
            name='institucion_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_1', to='catalogos.institucioneducativa'),
        ),
        migrations.AlterField(
            model_name='casosac',
            name='institucion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_institucion_2', to='catalogos.institucioneducativa'),
        ),
    ]
