# Generated by Django 6.0.5 on 2026-06-28 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0003_alter_casosac_num_radicado_sac_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casosac',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_sac_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
