# Generated by Django 6.0.5 on 2026-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('sector', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICA', max_length=10)),
                ('rector', models.CharField(max_length=255, verbose_name='Nombre del Rector')),
                ('num_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Contacto')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'ordering': ['nombre'],
            },
        ),
    ]
