# Generated by Django 6.0.5 on 2026-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion_educativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institucioneducativa',
            table='institucion_educativa',
        ),
    ]
